name: "Build Development Docker Image"

on:
  workflow_dispatch:

jobs:
  buildimage:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v3

      - name: Get Arguments for Docker Build
        shell: |
          export DOCKER_ARGUMENTS=$(cat .env.dockerfile.development |  tr '\n' ' ')
          echo "::set-env name=DOCKER_ARGUMENTS::$DOCKER_ARGUMENTS"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: registry.hub.docker.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Build docker image and push to registry
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: pepitoenpeligro/flutter-dev
          context: .
          build-args: $DOCKER_ARGUMENTS
          file: Dockerfile.development
          platforms: linux/amd64,linux/arm64
          