name: "Testing Private Windows CI Server Runner"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Enter environment for deployment: dev, qa or pro'
        required: true
        default: 'dev'


jobs:
  somejob:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v3

      - name: Credentials to DEV Environment
        if: ${{ github.event.inputs.environment=='dev' }}
        run: | 
           echo "AKID=${{ secrets.CHEM_AWS_DEV_AK }}" >> $GITHUB_ENV
           echo "SKID=${{ secrets.CHEM_AWS_DEV_SK }}">> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ env.AKID }}
          aws-secret-access-key: ${{ env.SKID }}
          aws-region: eu-west-1
      - name: Start SSM Session
        run: aws ssm start-session --region 'eu-west-1' \
              --target 'i-040f8582e37915507' \
              --document-name AWS-StartPortForwardingSessionToRemoteHost \
              --parameters portNumber="443",localPortNumber="443" &
      - name: Get list of rules
        shell: pwsh
        run: |
          HOSTNAME