name: "Deploy to AWS Amplify"

on:
    push:
      paths:
        - 'lib/**'
        - '.github/workflows/publish_amplify.yaml'
  
jobs:
    deploy:
        permissions:
            id-token: write
            contents: read
        runs-on: ubuntu-latest


        steps:
            - uses: actions/checkout@v3

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                audience: 'sts.amazonaws.com'
                aws-region: eu-west-1
                role-session-name: GitHubActions
                role-to-assume: "${{ secrets.AWS_GITHUB_AMPLIFY_ROLE }}"
                role-duration-seconds: 1500
                mask-aws-account-id: true


            - name: Create web artifact bundle
              shell: bash
              run: |
                docker run -v `pwd`:/home/dementiapp --rm pepitoenpeligro/flutter-dev:latest flutter pub get && flutter build web
                
            
            - name: Install zip
              uses: montudor/action-zip@v1

            - name: Compress web artifact bundle as zaip
              run: zip -qq -r location.zip build/web/*
              working-directory: ./

            - name: Upload to private bucket
              run: |
                aws s3 cp ./location.zip s3://location-web-app
                # subir a s3 como zip

            - name: Start Deployment to Amplifyy
              shell: bash
              run: |
                    AMPLIFY_APP_ID=$(aws amplify list-apps | jq -r '.apps[] | select((.name=="Location")) | .appId')
                    AMPLIFY_APP_BRANCH=$(aws amplify list-apps | jq -r '.apps[] | select((.name=="Location")) | .productionBranch.branchName')
                    aws amplify start-deployment \
                    --app-id $AMPLIFY_APP_ID \
                    --branch-name AMPLIFY_APP_BRANCH \
                    --source-url s3://location-web-app/location-web-app.zip