name: "Deploy to AWS Amplify"

on:
    push:
      paths:
        - 'lib/**'
        - '.github/workflows/publish_amplify.yaml'
  
jobs:
    deploy:
        permissions:
            id-token: write
            contents: read
        runs-on: ubuntu-latest


        steps:
            - uses: actions/checkout@v3

            - name: Compound session name
              shell: bash
              run: |
               SESSION_NAME=${GITHUB_ACTOR}-${GITHUB_REPOSITORY}-${GITHUB_SHA::7} 
               echo "SESSION_NAME=$SESSION_NAME" >> $GITHUB_ENV
               echo $SESSION_NAME

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                aws-region: eu-west-1
                role-session-name: $SESSION_NAME
                role-to-assume: ${{ secrets.AWS_GITHUB_AMPLIFY_ROLE }}
                role-duration-seconds: 1500
                mask-aws-account-id: true


            - name: List AWS Amplify
              shell: bash
              run: |
                aws amplify list-apps 